require('dotenv').config()
const express = require('express')
const connection = require('./db')
const cors = require('cors')
const userListRoutes = require("./routes/getUsersByToken")
 const tokenVerification = require('./middleware/tokenVerification')
const userRoutes = require("./routes/users")
const authRoutes = require("./routes/auth")
const app = express()
app.use(express.json())
app.use(cors())
app.use("/api/users", userRoutes)
app.use("/api/auth", authRoutes)
app.use(tokenVerification)
app.use("/api/userlist", userListRoutes)

connection()
const port = process.env.PORT || 8080
app.listen(port, () => console.log(`Nasłuchiwanie na porcie ${port}`))